enum SeatChoice {
  AISLE = "AISLE",
  MIDDLE = "MIDDLE",
  WINDOW = "WINDOW",
}

const mySeat = SeatChoice.WINDOW

const enum SeatChoice2 {  // we can use const to avoid typescript to generate more code
  AISLE = "AISLE",
  MIDDLE = "MIDDLE",
  WINDOW = "WINDOW",
}

const mySeat2 = SeatChoice2.AISLE
const mySeat3 = SeatChoice2.WINDOW

// javascript generated by typescript when using const enum
// const mySeat = "WINDOW" /* SeatChoice.WINDOW */;
// const mySeat2 = "AISLE" /* SeatChoice.AISLE */;
